service: taskmaster
frameworkVersion: '3'

useDotenv: true

custom:
  stage: ${opt:stage, self:provider.stage}
  appName: ar-pdf-service

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-southeast-1
  memorySize: 3008
  versionFunctions: false
  environment:
    REGION: ${self:provider.region}
    STAGE: ${self:custom.stage}
    MONGO_DB_URI: ${env:MONGO_DB_URI}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_APP_CLIENT_ID: ${env:COGNITO_APP_CLIENT_ID}
    DEFAULT_PORT: ${env:DEFAULT_PORT}
  logs:
    restApi: true

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  graphql:
    handler: bin/server
    timeout: 30
    name: ${self:custom.appName}-${self:custom.stage}-graphql
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:AdminInitiateAuth
          - cognito-idp:AdminCreateUser
          - cognito-idp:AdminConfirmSignUp
          - cognito-idp:AdminSetUserPassword
        Resource: 
          - "*"

plugins:
  - serverless-iam-roles-per-function